### ISSUE TITLE
Option to change input folder from GUI

### ISSUE THREAD

**Issue by flesnuk** [arenatemp/sd-tagging-helper#17]
I didn't find a way to change the input folder without manually editing the start.sh arguments. 
Maybe a good time would be after packaging to the output folder. (Infering that you finished with the current dataset and want to go to next one). Possible by adding a button in the package pop-up instead of displaying the File explorer automatically to avoid confussion. (by thinking it is requesting the output folder)

But the best option is having a toolbar with the typical File, View, etc. improving the usability/friendliness of the program.

**Comment by arenasys** [comment]
Yea, its not ready to be done automatically without side effects, so i left it as a manual only option.

The issue is changing the input folder without changing the staging folder can currently have unexpected results.
if you have `input_a/1.png` and `input_b/1.png` they will both share the staging metadata file `1.png.json`, overriding each other. Also it may be unexpected to have the output data overridden.

Asking for each of the 3 folders from the user is annoying and confusing so theres two options i can think of.
- fix the staging folder layout so each input folder is isolated, and keep the output folder shared.
- have the program automatically create staging and output folders in whatever input folder you select, this could be annoying to some users that dont want their inputs to be messed with, but theres always the option to manually specify.

**Comment by flesnuk** [comment]
The best would be to ask the user to input a name for the dataset they will work on, or just use the name of the input folder as the dataset name. Then you can use that as a way to store in output/datasetname or staging/datasetname

**Comment by arenasys** [comment]
A dataset name is good solution but i want to try keep everything as straightforward as possible.
Having the output+staging folder in the input folder has a few advantages. The datasets would be totally isolated from each other and portable, the structure is easier to understand/manage for the user and the only information the user needs to provide is the input folder. So i will probably go with that

**Comment by arenasys** [comment]
added in b03599b1e8583b3d0b5ddf2622821a62336da9f3
